apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-configuration
  labels:
    app: pgadmin4
data:
  PGADMIN_DEFAULT_EMAIL: devops.manuel@gmail.com
  PGADMIN_DEFAULT_PASSWORD: devopsmanuel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4-deployment
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:latest
        envForm:
        - configMapRef:
            name: pgadmin4-configuration
        ports:
        - containerPort: 80
          name: pgadmin4
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-service
  labels:
    app: pgadmin4
spec:
  ports:
  - port: 80
    name: pgadmin4
  selector:
    app: pgadmin4
