apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-configuration
  labels:
    app: pgadmin4
data:
  PGADMIN_DEFAULT_EMAIL: devops.manuel@gmail.com
  PGADMIN_DEFAULT_PASSWORD: devopsmanuel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4-deployment
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:latest
        envFrom:
        - configMapRef:
            name: pgadmin4-configuration
        ports:
        - containerPort: 80
          name: pgadmin4
        volumeMounts:
        - name: pv-pgadmin4
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pv-pgadmin4
        persistentVolumeClaim:
          claimName: pgadmin4-pv-claim
      initContainers:
        - name: pgadmin-data-permission-fix
          image: busybox
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"]
          volumeMounts:
          - name: pv-pgadmin4
            mountPath: /var/lib/pgadmin
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-service
  labels:
    app: pgadmin4
spec:
  ports:
  - port: 80
    name: pgadmin4
  selector:
    app: pgadmin4
